language: java
jdk:
  - openjdk8
deploy:
  provider: heroku
  api-key:
    secure: "ueGrqILWCvGNEludK627qNAWaJ1/MmCE2C9tepyUA52sHh5ustb0I4dBvOI159ib6OJ1qBZwFCc7Gw4uP2FTvnfymJ4ETZsqO9URtBq8s76jfPFNnNBP7s58+ApMMc1+/syyYJTRg08Mdevhnkt0Y8kIH6ibbveolasfwPahd2peMO/ktlDPi/svqGyt
    eEnLGL9mFJ49eZGV4AS8TrWwSwtP+MrQanDBhaZZKvSudJHX5gNpgo0wDeJ1kXbuz5PkQIDAKJsXUjMBch7O3lB61GmYkc0XX3GG1SMXkfhnarVJpGu9dvBlkCpd8z9BlZa2TQec2LD3Yqv0TM+o6HEpylWhDJRMpJF5SJQHBAFj+2jMi/EUqqbqeGITpdWBVj9go7J
    N6MZxPzc2BkvzxZKj9TIcbu5nS6oQ0mMwaksAZhr8XJwY4sruMwam4Hn3tqyh2iZ5PkOggFpeCNAoM0RiYQxEjqsppSD4tjghiNJhaxrjavgZJcHn3v1heAvWS3jQoK4wTxxhYUh54hdqcMqdzMsT2IbT1gLIGURzN1V8iOn7AEFQSWC+7jZPhnEmHwSvw5RJSPd7HB
    FcdRQHWssn6G5S+D6yqcb/xdPRs4Y0/7FInNZWMUP6X+W6xkyZXwS3PM9/XGCfJdDOaMyadeiu8QmdXpBIBzv1WmT3Vwyj5RY="
  app: chuck-norris-facts-feeder